// Approved domains for the guardrailed search (mirrored server-side in app/api/search/route.js)
export const APPROVED_SITES = ["binbaz.org.sa", "binothaimeen.net", "dorar.net", "aliftaksa.com", "islamweb.net"];

// Google Programmable Search Engine id (public client id — safe in the browser).
export const PSE_CX = "3005da932b77b48ee";

// Site contact address (used for the content/rights notice and the footer).
export const CONTACT_EMAIL = "muslimsummah.app@gmail.com";

// Stable URL slug for a book (derived from its file name), used for permanent /library/[slug] pages.
export function bookSlug(b) {
  return (b.fileAr || "").split("/").pop().replace(/\.pdf$/i, "");
}

export const CATS = [
  { key: "all", ar: "الكل", en: "All" },
  { key: "ali", ar: "كتب ومقالات علي", en: "Ali's Books & Articles" },
  { key: "aqidah", ar: "عقيدة", en: "Creed" },
  { key: "hadith", ar: "حديث", en: "Hadith" },
  { key: "life", ar: "الحياة مع الله", en: "Life with Allah" },
];

// Place the actual PDFs in /public/books/ with these filenames.
export const BOOKS = [
  {
    id: 9, cat: "ali", bilingual: true, pages: 41, size: "7.9 MB",
    fileAr: "/books/muqaddimah-fi-ilm-alhadith-ar.pdf",
    fileEn: "/books/introduction-to-hadith-en.pdf",
    title: { ar: "مقدمة في علم الحديث", en: "Introduction to Hadith" },
    author: { ar: "علي عبد العزيز الصدّيقي رحمه الله — بمشاركة محمد الصدّيقي", en: "Ali Abdulaziz Alseddiqi (may Allah have mercy on him), with Mohammad Alseddiqi" },
    desc: { ar: "مدخل ميسّر إلى علم الحديث ومصطلحه. متاح بالعربية والإنجليزية، ويجوز نشره مجانًا للأغراض التعليمية.", en: "An accessible introduction to the science of Hadith and its terminology. Available in Arabic and English, free to share for educational use." },
  },

  // ── مكتبة إنجليزية: كلها مصنّفة "عقيدة" مؤقتًا (English library — all under "aqidah" for now) ──
  {
    id: 12, cat: "aqidah", lang: "en", pages: 82, size: "15.1 MB",
    fileAr: "/books/three-fundamental-principles-en.pdf",
    title: { ar: "الأصول الثلاثة (نسخة موضّحة)", en: "The Three Fundamental Principles (Illustrated)" },
    author: { ar: "الإمام محمد بن عبد الوهاب رحمه الله", en: "Imam Muhammad ibn Abdul-Wahhab" },
    desc: { ar: "متن الأصول الثلاثة في توحيد العبادة، نسخة إنجليزية موسّعة وموضّحة. (الكتاب باللغة الإنجليزية)", en: "The foundational treatise on the three principles every Muslim must know — an expanded, illustrated English edition." },
  },
  {
    id: 13, cat: "aqidah", lang: "en", pages: 22, size: "0.4 MB",
    fileAr: "/books/three-fundamental-principles-ibaanah-en.pdf",
    title: { ar: "الأصول الثلاثة (ترجمة الإبانة)", en: "The Three Fundamental Principles (Al-Ibaanah)" },
    author: { ar: "الإمام محمد بن عبد الوهاب رحمه الله — ترجمة أبي مريم إسماعيل ألاركون", en: "Imam Muhammad ibn Abdul-Wahhab — tr. Abu Maryam Isma'eel Alarcon" },
    desc: { ar: "ترجمة إنجليزية مختصرة وواضحة لمتن الأصول الثلاثة. (الكتاب باللغة الإنجليزية)", en: "A concise, clear English translation of the classic three-principles text." },
  },
  {
    id: 14, cat: "aqidah", lang: "en", pages: 79, size: "0.5 MB",
    fileAr: "/books/aqidah-wasitiyyah-en.pdf",
    title: { ar: "العقيدة الواسطية (إنجليزي)", en: "Al-Aqidah Al-Wasitiyyah (English)" },
    author: { ar: "شيخ الإسلام ابن تيمية رحمه الله", en: "Shaykh al-Islam Ibn Taymiyyah" },
    desc: { ar: "متن في اعتقاد أهل السنة والجماعة في أسماء الله وصفاته، بنص عربي وترجمة إنجليزية. (الكتاب باللغة الإنجليزية)", en: "The creed of Ahl as-Sunnah on Allah's names and attributes, with Arabic text and English translation." },
  },
  {
    id: 15, cat: "aqidah", lang: "en", pages: 86, size: "1.2 MB",
    fileAr: "/books/foundations-of-faith-en.pdf",
    title: { ar: "شرح أصول الإيمان", en: "Explaining the Foundations of Faith" },
    author: { ar: "الشيخ محمد بن صالح العثيمين رحمه الله", en: "Shaykh Muhammad ibn Salih al-Uthaymeen" },
    desc: { ar: "شرح ميسّر لأركان الإيمان الستة وأصول العقيدة. (الكتاب باللغة الإنجليزية)", en: "An accessible explanation of the six pillars of faith and the foundations of creed." },
  },
  {
    id: 16, cat: "aqidah", lang: "en", pages: 90, size: "3.7 MB",
    fileAr: "/books/creed-of-four-imams-en.pdf",
    title: { ar: "اعتقاد الأئمة الأربعة", en: "The Creed of the Four Imams" },
    author: { ar: "د. محمد بن عبد الرحمن الخميس", en: "Dr. Muhammad ibn Abdur-Rahman al-Khumayyis" },
    desc: { ar: "بيان أن أئمة المذاهب الأربعة على عقيدة واحدة في الأصول. (الكتاب باللغة الإنجليزية)", en: "Demonstrating that the four great Imams shared one creed in the fundamentals." },
  },
  {
    id: 17, cat: "aqidah", lang: "en", pages: 21, size: "0.7 MB",
    fileAr: "/books/tafseer-kalimah-tawheed-en.pdf",
    title: { ar: "تفسير كلمة التوحيد", en: "Tafseer of the Statement of Tawheed" },
    author: { ar: "العلامة ربيع بن هادي المدخلي", en: "Al-Allamah Rabee' ibn Haadee al-Madkhalee" },
    desc: { ar: "بيان معنى لا إله إلا الله وشروطها ومقتضاها. (الكتاب باللغة الإنجليزية)", en: "Explaining the meaning, conditions, and implications of 'La ilaha illa Allah'." },
  },
  {
    id: 18, cat: "aqidah", lang: "en", pages: 30, size: "0.6 MB",
    fileAr: "/books/understanding-of-the-salaf-en.pdf",
    title: { ar: "فهم السلف الصالح", en: "Understanding of the Salaf" },
    author: { ar: "شهباز أحمد طور", en: "Shahbaz Ahmed Toor" },
    desc: { ar: "أهمية فهم السلف الصالح في تلقّي الدين والاستدلال. (الكتاب باللغة الإنجليزية)", en: "Why the understanding of the righteous predecessors is the key to rightly grasping the religion." },
  },
  {
    id: 19, cat: "aqidah", lang: "en", pages: 40, size: "0.8 MB",
    fileAr: "/books/isis-catastrophe-en.pdf",
    title: { ar: "داعش: نازلة وفتنة", en: "ISIS-Daesh: A Catastrophe and a Tribulation" },
    author: { ar: "الشيخ حسين المدني", en: "Shaykh Hussain Madani" },
    desc: { ar: "ردٌّ علمي على فكر الخوارج المعاصر وبيان خطره على الأمة. (الكتاب باللغة الإنجليزية)", en: "A scholarly refutation of contemporary extremist (Khawarij) ideology and its dangers." },
  },
  {
    id: 20, cat: "aqidah", lang: "en", pages: 59, size: "14.4 MB",
    fileAr: "/books/simple-guide-to-prayer-en.pdf",
    title: { ar: "دليل مبسّط للصلاة", en: "A Simple Guide to Prayer" },
    author: { ar: "منشورات سلفية", en: "Salafi Publications" },
    desc: { ar: "دليل مصوّر خطوة بخطوة لأداء الصلاة، مناسب للمسلم الجديد. (الكتاب باللغة الإنجليزية)", en: "An illustrated, step-by-step guide to performing the prayer — ideal for new Muslims." },
  },
  {
    id: 21, cat: "aqidah", lang: "en", pages: 52, size: "0.5 MB",
    fileAr: "/books/common-questions-about-islam-en.pdf",
    title: { ar: "أجوبة عن أسئلة غير المسلمين الشائعة", en: "Answers to Non-Muslims' Common Questions" },
    author: { ar: "د. ذاكر نايك", en: "Dr. Zakir Naik" },
    desc: { ar: "إجابات موجزة عن أكثر الأسئلة شيوعًا حول الإسلام. (الكتاب باللغة الإنجليزية)", en: "Concise answers to the most frequently raised questions about Islam." },
  },

  // ── سلسلة «الحياة مع الله» — إصدار Ummah Welfare Trust (Life with Allah series) ──
  {
    id: 22, cat: "life", lang: "en", pages: 198, size: "5.0 MB",
    fileAr: "/books/life-salah-en.pdf",
    title: { ar: "الصلاة", en: "Salah — The Prayer" },
    author: { ar: "إصدار Ummah Welfare Trust", en: "Ummah Welfare Trust" },
    desc: { ar: "دليل عملي شامل للصلاة: صفتها وأحكامها وأسرارها، بنصوص عربية وشرح إنجليزي. (الكتاب باللغة الإنجليزية)", en: "A complete practical guide to the prayer — its method, rulings, and inner meanings." },
  },
  {
    id: 23, cat: "life", lang: "en", pages: 142, size: "3.3 MB",
    fileAr: "/books/life-daily-adhkar-en.pdf",
    title: { ar: "الأذكار اليومية", en: "Daily Adhkar" },
    author: { ar: "إصدار Ummah Welfare Trust", en: "Ummah Welfare Trust" },
    desc: { ar: "الأذكار والأدعية الثابتة عن النبي ﷺ لليوم والليلة (الجزء الأول من السلسلة). (الكتاب باللغة الإنجليزية)", en: "Authentic daily remembrances and supplications of the Prophet ﷺ (Series Book One)." },
  },
  {
    id: 24, cat: "life", lang: "en", pages: 140, size: "7.5 MB",
    fileAr: "/books/life-adhkar-two-en.pdf",
    title: { ar: "الأذكار — الجزء الثاني", en: "Adhkar — Book Two" },
    author: { ar: "إصدار Ummah Welfare Trust", en: "Ummah Welfare Trust" },
    desc: { ar: "تتمة الأذكار والأدعية لمناسبات وأحوال متعددة (الجزء الثاني من السلسلة). (الكتاب باللغة الإنجليزية)", en: "A continuation of remembrances and supplications for various occasions (Series Book Two)." },
  },
  {
    id: 25, cat: "life", lang: "en", pages: 16, size: "0.7 MB",
    fileAr: "/books/life-ruqyah-en.pdf",
    title: { ar: "الرقية الشرعية", en: "Ruqyah" },
    author: { ar: "إصدار Ummah Welfare Trust", en: "Ummah Welfare Trust" },
    desc: { ar: "العلاج بالقرآن والأدعية النبوية من العين والسحر والمسّ، مع الآيات والأذكار. (الكتاب باللغة الإنجليزية)", en: "Treatment through Qur'anic verses and prophetic supplications for the evil eye, magic, and ailments." },
  },
  {
    id: 26, cat: "life", lang: "en", pages: 36, size: "1.1 MB",
    fileAr: "/books/life-surah-al-fatihah-en.pdf",
    title: { ar: "سورة الفاتحة", en: "Surah Al-Fatihah" },
    author: { ar: "إصدار Ummah Welfare Trust", en: "Ummah Welfare Trust" },
    desc: { ar: "وقفات مع فاتحة الكتاب: معانيها وعظمتها ومكانتها في الصلاة. (الكتاب باللغة الإنجليزية)", en: "Reflections on the Opening Surah — its meanings, greatness, and place in the prayer." },
  },

  // ── علوم الحديث ومصطلحه وشروحه (Hadith sciences & commentaries) ──
  {
    id: 27, cat: "hadith", lang: "en", pages: 117, size: "14.8 MB",
    fileAr: "/books/hadith-nukhbatul-fikr-en.pdf",
    title: { ar: "نخبة الفِكَر", en: "Nukhbat al-Fikar" },
    author: { ar: "الحافظ ابن حجر العسقلاني", en: "Al-Hafiz Ibn Hajar al-Asqalani" },
    desc: { ar: "متن مختصر بديع في مصطلح الحديث، أصل لكثير من كتب المصطلح. (الكتاب باللغة الإنجليزية)", en: "A concise masterwork on hadith terminology that became a foundation for the field." },
  },
  {
    id: 28, cat: "hadith", lang: "en", pages: 59, size: "0.2 MB",
    fileAr: "/books/hadith-mustalah-uthaymeen-en.pdf",
    title: { ar: "مصطلح الحديث", en: "Terminology of Hadith" },
    author: { ar: "الشيخ محمد بن صالح العثيمين رحمه الله", en: "Shaykh Muhammad ibn Salih al-Uthaymeen" },
    desc: { ar: "مدخل ميسّر إلى مصطلح الحديث وأقسامه. (الكتاب باللغة الإنجليزية)", en: "An accessible introduction to the terminology and categories of hadith." },
  },
  {
    id: 29, cat: "hadith", lang: "en", pages: 644, size: "28.6 MB",
    fileAr: "/books/hadith-jami-ulum-wal-hikam-en.pdf",
    title: { ar: "جامع العلوم والحِكَم", en: "A Collection of Knowledge and Wisdom" },
    author: { ar: "الإمام ابن رجب الحنبلي", en: "Imam Ibn Rajab al-Hanbali" },
    desc: { ar: "شرح جامع لأحاديث جوامع الكلم من الأربعين النووية وزيادة. (الكتاب باللغة الإنجليزية)", en: "A comprehensive commentary on the comprehensive hadiths of the Nawawi collection and beyond." },
  },
  {
    id: 30, cat: "hadith", lang: "en", pages: 190, size: "59 MB",
    fileAr: "/books/hadith-explanation-40-nawawi-p1-en.pdf",
    title: { ar: "شرح الأربعين النووية — الجزء الأول", en: "Explanation of the 40 Nawawi — Part 1" },
    author: { ar: "الشيخ صالح الفوزان", en: "Shaykh Salih al-Fawzan" },
    desc: { ar: "شرح علمي مأصول للأربعين النووية (الجزء الأول). (الكتاب باللغة الإنجليزية)", en: "A grounded scholarly explanation of the forty hadith of Imam Nawawi (Part 1)." },
  },
  {
    id: 32, cat: "hadith", lang: "en", pages: 191, size: "56 MB",
    fileAr: "/books/hadith-explanation-40-nawawi-p2-en.pdf",
    title: { ar: "شرح الأربعين النووية — الجزء الثاني", en: "Explanation of the 40 Nawawi — Part 2" },
    author: { ar: "الشيخ صالح الفوزان", en: "Shaykh Salih al-Fawzan" },
    desc: { ar: "شرح علمي مأصول للأربعين النووية (الجزء الثاني). (الكتاب باللغة الإنجليزية)", en: "A grounded scholarly explanation of the forty hadith of Imam Nawawi (Part 2)." },
  },
  {
    id: 31, cat: "hadith", pages: 600, size: "21.7 MB",
    fileAr: "/books/hadith-fath-albari-vol1-ar.pdf",
    title: { ar: "فتح الباري — المجلد الأول", en: "Fath al-Bari — Volume 1" },
    author: { ar: "الحافظ ابن حجر العسقلاني", en: "Al-Hafiz Ibn Hajar al-Asqalani" },
    desc: { ar: "أعظم شروح صحيح البخاري — المجلد الأول (عربي).", en: "The greatest commentary on Sahih al-Bukhari — Volume 1 (Arabic)." },
  },
];

// Place the actual MP3s in /public/audio/ with these filenames.
export const TRACKS = [
  { id: 1, dur: 72, src: "/audio/al-fatihah.mp3", tag: { ar: "قرآن كريم", en: "Qur'an" },
    title: { ar: "سورة الفاتحة", en: "Surah Al-Fatihah" },
    sub: { ar: "تلاوة مرتلة — رواية حفص عن عاصم", en: "Measured recitation — Hafs 'an 'Asim" } },
  { id: 2, dur: 225, src: "/audio/takbeerat-aleid.mp3", tag: { ar: "شعائر", en: "Rites" },
    title: { ar: "تكبيرات العيد", en: "Eid Takbeerat" },
    sub: { ar: "التكبيرات الجماعية — صيغة مطلقة ومقيدة", en: "Congregational takbeer — general and restricted forms" } },
  { id: 3, dur: 750, src: "/audio/adhkar-alsabah.mp3", tag: { ar: "أذكار", en: "Adhkar" },
    title: { ar: "أذكار الصباح", en: "Morning Adhkar" },
    sub: { ar: "الأذكار الثابتة في الصحيحين والسنن", en: "Authentic remembrances from the Sahihayn and Sunan" } },
  { id: 4, dur: 494, src: "/audio/al-mulk.mp3", tag: { ar: "قرآن كريم", en: "Qur'an" },
    title: { ar: "سورة الملك", en: "Surah Al-Mulk" },
    sub: { ar: "تلاوة خاشعة — المنجية بإذن الله", en: "A serene recitation — the Protector, by Allah's leave" } },
];

export const YT_CHANNELS = [
  { id: 0, official: true, url: "https://www.youtube.com/@For_AliAlseddiqi", handle: "@For_AliAlseddiqi",
    name: { ar: "قناة علي الصدّيقي", en: "Ali Alseddiqi Channel" },
    topic: { ar: "القناة الرسمية للموقع — مواد علي عبد العزيز الصدّيقي رحمه الله المرئية والصوتية", en: "The network's official channel — video and audio works of Ali Abdulaziz Alseddiqi, may Allah have mercy on him" } },
  { id: 4, url: "https://www.youtube.com/@baytalathaar", handle: "@baytalathaar",
    name: { ar: "أبو عبيدة بن رشيد الباكستاني", en: "Abu Ubayda Al-Pakistani" },
    topic: { ar: "دروس في العقيدة والحديث", en: "Lessons in creed and hadith" } },
  { id: 5, url: "https://www.youtube.com/@fatwa-online", handle: "@fatwa-online",
    name: { ar: "Fatwa-Online", en: "Fatwa-Online" },
    topic: { ar: "فتاوى كبار العلماء مترجمة", en: "Translated fatwas of senior scholars" } },
  { id: 6, url: "https://www.youtube.com/@fawaidraslan", handle: "@fawaidraslan",
    name: { ar: "فوائد رسلان", en: "Fawaid Raslan" },
    topic: { ar: "فوائد ودروس الشيخ رسلان", en: "Benefits and lessons of Shaykh Raslan" } },
  { id: 7, url: "https://www.youtube.com/@gtownmasjid", handle: "@gtownmasjid",
    name: { ar: "Germantown Masjid", en: "Germantown Masjid" },
    topic: { ar: "دروس ومحاضرات سلفية", en: "Salafi lessons and lectures" } },
  { id: 8, url: "https://www.youtube.com/@daarussunnah", handle: "@daarussunnah",
    name: { ar: "مسجد دار السنة", en: "Masjid Daar us Sunnah" },
    topic: { ar: "دروس ومحاضرات علمية", en: "Knowledge lessons and lectures" } },
  { id: 9, url: "https://www.youtube.com/@masjidsunnahnelson", handle: "@masjidsunnahnelson",
    name: { ar: "Masjid Sunnah Nelson", en: "Masjid Sunnah Nelson" },
    topic: { ar: "دروس ومحاضرات", en: "Lessons and lectures" } },
  { id: 10, url: "https://www.youtube.com/@nesmudawah", handle: "@nesmudawah",
    name: { ar: "Nesmu Dawah", en: "Nesmu Dawah" },
    topic: { ar: "دعوة ومقاطع مترجمة", en: "Da'wah and translated clips" } },
  { id: 11, url: "https://www.youtube.com/@scholarly_subtitles", handle: "@scholarly_subtitles",
    name: { ar: "Scholarly Subtitles", en: "Scholarly Subtitles" },
    topic: { ar: "مقاطع العلماء مترجمة", en: "Subtitled scholarly clips" } },
  { id: 12, url: "https://www.youtube.com/@sheikhazizbinfarhanalanizi2452", handle: "@sheikhazizbinfarhanalanizi2452",
    name: { ar: "الشيخ عزيز بن فرحان العنزي", en: "Shaykh Aziz Al-Anizi" },
    topic: { ar: "دروس وفتاوى علمية", en: "Lessons and fatwas" } },
  { id: 13, url: "https://www.youtube.com/@theguidedpath1", handle: "@theguidedpath1",
    name: { ar: "The Guided Path", en: "The Guided Path" },
    topic: { ar: "محتوى دعوي مترجم", en: "Translated da'wah content" } },
  { id: 14, url: "https://www.youtube.com/@treasuresofknowledge", handle: "@treasuresofknowledge",
    name: { ar: "Treasures of Knowledge", en: "Treasures of Knowledge" },
    topic: { ar: "كنوز ودرر علمية", en: "Knowledge treasures" } },
  { id: 15, url: "https://www.youtube.com/@peopleofknowledge1", handle: "@peopleofknowledge1",
    name: { ar: "People of Knowledge", en: "People of Knowledge" },
    topic: { ar: "مقاطع أهل العلم", en: "Clips of the people of knowledge" } },
  { id: 16, url: "https://www.youtube.com/@rabbaniyeen", handle: "@rabbaniyeen",
    name: { ar: "Rabbaniyeen Translations", en: "Rabbaniyeen Translations" },
    topic: { ar: "ترجمات علمية موثوقة", en: "Reliable scholarly translations" } },
  { id: 17, url: "https://www.youtube.com/@-theshipofsalvation", handle: "@-theshipofsalvation",
    name: { ar: "The Ship of Salvation", en: "The Ship of Salvation" },
    topic: { ar: "محتوى دعوي وعلمي", en: "Da'wah and knowledge content" } },
];

export const IG_PROFILES = [
  { id: 5, handle: "sheikhalbaadr", url: "https://www.instagram.com/sheikhalbaadr",
    name: { ar: "الشيخ عبدالرزاق البدر", en: "Shaykh Abdurrazzaq al-Badr" },
    focus: { ar: "دروس ومقاطع الشيخ عبدالرزاق البدر", en: "Lessons and clips of Shaykh al-Badr" } },
  { id: 6, handle: "abu.zakariyya_", url: "https://www.instagram.com/abu.zakariyya_",
    name: { ar: "أبو زكريا", en: "Abu Zakariyya" },
    focus: { ar: "محتوى دعوي وعلمي", en: "Da'wah and knowledge" } },
  { id: 7, handle: "smr22ss", url: "https://www.instagram.com/smr22ss",
    name: { ar: "مقاطع سلفية", en: "Salafi Clips" },
    focus: { ar: "مقاطع علمية مختارة", en: "Selected knowledge clips" } },
  { id: 8, handle: "aluthaymeenen", url: "https://www.instagram.com/aluthaymeenen",
    name: { ar: "الشيخ ابن عثيمين (إنجليزي)", en: "Ibn Uthaymeen (EN)" },
    focus: { ar: "مقاطع الشيخ ابن عثيمين مترجمة", en: "Translated clips of Shaykh Ibn Uthaymeen" } },
  { id: 9, handle: "saalih.al.fawzan", url: "https://www.instagram.com/saalih.al.fawzan",
    name: { ar: "الشيخ صالح الفوزان", en: "Shaykh al-Fawzan" },
    focus: { ar: "فتاوى ومقاطع الشيخ الفوزان", en: "Fatwas and clips of Shaykh al-Fawzan" } },
  { id: 10, handle: "islamic.guider_", url: "https://www.instagram.com/islamic.guider_",
    name: { ar: "Islamic Guider", en: "Islamic Guider" },
    focus: { ar: "تذكير ودعوة", en: "Reminders and da'wah" } },
  { id: 11, handle: "gemsinenglish", url: "https://www.instagram.com/gemsinenglish",
    name: { ar: "Gems in English", en: "Gems in English" },
    focus: { ar: "درر علمية بالإنجليزية", en: "Knowledge gems in English" } },
  { id: 12, handle: "ibnbaz23", url: "https://www.instagram.com/ibnbaz23",
    name: { ar: "الشيخ ابن باز", en: "Shaykh Ibn Baz" },
    focus: { ar: "مقاطع وفتاوى الشيخ ابن باز", en: "Clips and fatwas of Shaykh Ibn Baz" } },
  { id: 13, handle: "shaykhibnqayyim", url: "https://www.instagram.com/shaykhibnqayyim",
    name: { ar: "الإمام ابن القيم", en: "Ibn al-Qayyim" },
    focus: { ar: "أقوال الإمام ابن القيم", en: "Words of Imam Ibn al-Qayyim" } },
  { id: 14, handle: "shaykhhasanalbasri", url: "https://www.instagram.com/shaykhhasanalbasri",
    name: { ar: "الحسن البصري", en: "al-Hasan al-Basri" },
    focus: { ar: "أقوال الحسن البصري والسلف", en: "Sayings of al-Hasan al-Basri and the Salaf" } },
  { id: 15, handle: "um.ilyaas", url: "https://www.instagram.com/um.ilyaas",
    name: { ar: "أم إلياس", en: "Um Ilyaas" },
    focus: { ar: "محتوى دعوي", en: "Da'wah content" } },
  { id: 16, handle: "shaykhibntaymiyyah", url: "https://www.instagram.com/shaykhibntaymiyyah",
    name: { ar: "شيخ الإسلام ابن تيمية", en: "Ibn Taymiyyah" },
    focus: { ar: "أقوال شيخ الإسلام ابن تيمية", en: "Words of Shaykh al-Islam Ibn Taymiyyah" } },
  { id: 17, handle: "shaykhfawzan", url: "https://www.instagram.com/shaykhfawzan",
    name: { ar: "الشيخ صالح الفوزان", en: "Shaykh al-Fawzan" },
    focus: { ar: "مقاطع الشيخ الفوزان", en: "Clips of Shaykh al-Fawzan" } },
  { id: 18, handle: "shaykhibnbaz", url: "https://www.instagram.com/shaykhibnbaz",
    name: { ar: "الشيخ ابن باز", en: "Shaykh Ibn Baz" },
    focus: { ar: "مقاطع الشيخ ابن باز", en: "Clips of Shaykh Ibn Baz" } },
  { id: 19, handle: "the_salaf_touch", url: "https://www.instagram.com/the_salaf_touch",
    name: { ar: "The Salaf Touch", en: "The Salaf Touch" },
    focus: { ar: "منهج السلف الصالح", en: "The way of the Salaf" } },
  { id: 20, handle: "ibn.uthaymeen", url: "https://www.instagram.com/ibn.uthaymeen",
    name: { ar: "الشيخ ابن عثيمين", en: "Shaykh Ibn Uthaymeen" },
    focus: { ar: "مقاطع الشيخ ابن عثيمين", en: "Clips of Shaykh Ibn Uthaymeen" } },
  { id: 21, handle: "shaykhalalbani", url: "https://www.instagram.com/shaykhalalbani",
    name: { ar: "الشيخ الألباني", en: "Shaykh al-Albani" },
    focus: { ar: "مقاطع وفتاوى الشيخ الألباني", en: "Clips and fatwas of Shaykh al-Albani" } },
  { id: 22, handle: "alhaqqan24", url: "https://www.instagram.com/alhaqqan24",
    name: { ar: "عبدالعزيز حقّان", en: "Abdulaziz Haqqan" },
    focus: { ar: "مقاطع الأستاذ عبدالعزيز حقّان", en: "Clips of Ustadh Abdulaziz Haqqan" } },
  { id: 23, handle: "sunnah.records", url: "https://www.instagram.com/sunnah.records",
    name: { ar: "Sunnah Records", en: "Sunnah Records" },
    focus: { ar: "مقاطع علمية مترجمة", en: "Translated knowledge clips" } },
  { id: 24, handle: "salafischolars.yemen", url: "https://www.instagram.com/salafischolars.yemen",
    name: { ar: "علماء اليمن السلفيون", en: "Salafi Scholars (Yemen)" },
    focus: { ar: "مقاطع علماء اليمن", en: "Clips of Yemen's scholars" } },
  { id: 25, handle: "gardenofilm_", url: "https://www.instagram.com/gardenofilm_",
    name: { ar: "Garden of ilm", en: "Garden of ilm" },
    focus: { ar: "حساب الأستاذ عبدالعزيز حقّان", en: "Account of Ustadh Abdulaziz Haqqan" } },
  { id: 26, handle: "athariaqeedah", url: "https://www.instagram.com/athariaqeedah",
    name: { ar: "Athari Aqeedah", en: "Athari Aqeedah" },
    focus: { ar: "العقيدة الأثرية", en: "Athari creed" } },
  { id: 27, handle: "treasure_of_knowledge.1", url: "https://www.instagram.com/treasure_of_knowledge.1",
    name: { ar: "Treasure of Knowledge", en: "Treasure of Knowledge" },
    focus: { ar: "كنوز علمية", en: "Knowledge treasures" } },
  { id: 28, handle: "salafi_haqq", url: "https://www.instagram.com/salafi_haqq",
    name: { ar: "Salafi Haqq", en: "Salafi Haqq" },
    focus: { ar: "محتوى سلفي", en: "Salafi content" } },
  { id: 29, handle: "shaykhibnuthaymin", url: "https://www.instagram.com/shaykhibnuthaymin",
    name: { ar: "الشيخ ابن عثيمين", en: "Shaykh Ibn Uthaymeen" },
    focus: { ar: "مقاطع الشيخ ابن عثيمين", en: "Clips of Shaykh Ibn Uthaymeen" } },
  { id: 30, handle: "noonespecial_3.0", url: "https://www.instagram.com/noonespecial_3.0",
    name: { ar: "No One Special", en: "No One Special" },
    focus: { ar: "تذكير ودعوة", en: "Reminders and da'wah" } },
  { id: 31, handle: "al.fawaid.publications", url: "https://www.instagram.com/al.fawaid.publications",
    name: { ar: "Al-Fawaid Publications", en: "Al-Fawaid Publications" },
    focus: { ar: "فوائد ومنشورات علمية", en: "Beneficial knowledge posts" } },
  { id: 32, handle: "scholarly_subtitles", url: "https://www.instagram.com/scholarly_subtitles",
    name: { ar: "Scholarly Subtitles", en: "Scholarly Subtitles" },
    focus: { ar: "مقاطع العلماء مترجمة", en: "Subtitled scholarly clips" } },
  { id: 33, handle: "salaf_as_saliheeen", url: "https://www.instagram.com/salaf_as_saliheeen",
    name: { ar: "Salaf as-Saliheen", en: "Salaf as-Saliheen" },
    focus: { ar: "منهج السلف الصالح", en: "The way of the righteous predecessors" } },
  { id: 34, handle: "bukharitvofficial", url: "https://www.instagram.com/bukharitvofficial",
    name: { ar: "Bukhari TV", en: "Bukhari TV" },
    focus: { ar: "محتوى علمي مرئي", en: "Visual knowledge content" } },
];
